name: RealPlugin
main: fr.crafter.tickleman.realplugin.RealPluginPlugin
version: 1.2.8
authors: [tickleman, Jakky89]
load: STARTUP
depend: [Vault]
commands:
  realplugin:
    aliases: [rp, relp]
    description: RealPlugin plugins manager
    usage: /rp help
  realrecipes:
    aliases: [rr, rer]
    description: Information commands about recipes
    usage: /rr dump
